noss:
    nexusProxy:
        enabled: false
    service:
        enabled: false
        port: 80
        targetPort: 8081
        type: NodePort
        readinessProbe:
            initialDelaySeconds: 120
            periodSeconds: 60
            failureThreshold: 6
        livenessProbe:
            initialDelaySeconds: 120
            periodSeconds: 60
    ingress:
        host: nexus.ticket721.com
        static_ip_name: noss-public

