{{- if .Values.jira.persistence.enabled }}
### Persistent Volume
apiVersion: v1
kind: PersistentVolume
metadata:
    name: "{{ .Release.Name }}-jira-pv"
    labels:
        app: "{{ .Release.Name }}-jira"
        chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
spec:
    storageClassName: ""
    capacity:
        storage: {{ .Values.jira.persistence.size }}
    accessModes:
        - ReadWriteOnce
        {{- if .Values.gcp }}
    gcePersistentDisk:
        pdName: jira-persistent
        fsType: ext4
        {{ else }}
    hostPath:
        path: /tmp
        {{ end }}
{{end}}
