apiVersion: v1
kind: PersistentVolume
metadata:
    name: "{{ .Release.Name }}-pv"
    labels:
        app: {{ template "dic.name" . }}
        chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
spec:
    storageClassName: manual
    capacity:
        storage: 50Gi
    volumeMode: Filesystem
    accessModes:
        - ReadWriteOnce
    hostPath:
        path: "/mnt/data"
